kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: datacentre
  name: glusterfs-cassandra-for-master
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
