apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: datacentre
  name: gluster-cassandra-volume-for-worker
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "k8s-volume"
    readOnly: false

