apiVersion: v1
kind: Service
metadata:
  labels:
    proxy: etcd
  name: etcd-proxy
spec:
  clusterIP: 10.254.100.100
  ports:
  - name: api 
    port: 2379
    targetPort: 2379
  - name: peer 
    port: 2380
    targetPort: 2380
  selector:
    component: etcd
